
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ovpn
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  persistentVolumeReclaimPolicy: Retain
  qcloudCbs:
    cbsDiskId: disk-0mr48u75
    fsType: ext4
  storageClassName: cbs
  volumeMode: Filesystem